
# SEO settings
title: Moses
description: "Fucking Big Data"
keywords: "Hadoop, Spark, Storm, Kafka, Akaka, BigData"
url: http://lifulong.me
# baseurl: "/simplest"
baseurl: null

google_analytics: UA-52446115-1
repo: http://github.com/lifulong/lifulong.github.io
disqus_shortname: "lifulong"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Moses
  job      : BigData Engineer
  bio      : "Nothing to say."
  thumb    : /images/author.jpg
  email    : msl.fulong@gmail.com
  url      : http://lifulong.me
  github   : http://github.com/lifulong
  twitter  : http://twitter.com/lifulong
  facebook : http://facebook.com/leefulong
  linkedin : http://linkedin.com/in/lifulong

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@leefulong"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
